ALTER TABLE Seat
DROP FOREIGN KEY seat_ibfk_1;


ALTER TABLE Seat
DROP COLUMN showtimeId,
DROP COLUMN isReserved;

CREATE TABLE ShowtimeSeat (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seatId BIGINT NOT NULL,
    showtimeId BIGINT NOT NULL,
    isReserved BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (seatId, showtimeId),
    FOREIGN KEY (seatId) REFERENCES Seat(id) ON DELETE CASCADE,
    FOREIGN KEY (showtimeId) REFERENCES Showtime(id) ON DELETE CASCADE
);
