ALTER TABLE Movie
MODIFY COLUMN description TEXT NOT NULL,
MODIFY COLUMN duration VARCHAR(50) NOT NULL,
MODIFY COLUMN genre VARCHAR(50) NOT NULL,
MODIFY COLUMN movieRating ENUM('G', 'PG', 'PG_13', 'R', 'NC_17') NOT NULL;