ALTER TABLE Showtime
ADD COLUMN movieId BIGINT NOT NULL;

ALTER TABLE Showtime
ADD COLUMN theatreId BIGINT NOT NULL;

ALTER TABLE Showtime
ADD CONSTRAINT FK_Showtime_Movie
FOREIGN KEY (movieId) REFERENCES Movie(id) ON DELETE CASCADE;

ALTER TABLE Showtime
ADD CONSTRAINT FK_Showtime_Theatre
FOREIGN KEY (theatreId) REFERENCES Theatre(id) ON DELETE CASCADE;